image: debian:buster-slim

pages:
  script:
    - apt-get update
    - apt-get install -y python3-dev python3-numpy python3-scipy python3-biopython python3-pip python3-matplotlib
    - apt-get install -y make
    - pip3 install sphinx
    - pip3 install sphinx_rtd_theme
    - make -C docs dirhtml
    - mv docs/build/dirhtml public/ 
  artifacts:
    paths:
      - public
  only:
    - master
